### PR TITLE
Rebuild for proj-6.2.1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
It doesn't look like the `proj` dependency is propagating to the individual packages correctly:
```
$ conda search --info datumgrid
proj-datumgrid-europe 1.3 0
---------------------------
file name   : proj-datumgrid-europe-1.3-0.tar.bz2
name        : proj-datumgrid-europe
version     : 1.3
build       : 0
build number: 0
size        : 18.2 MB
license     : Public domain | X/MIT | BSD-2/3/4-Clause | CC0 | CC-BY (v3.0 or later) | CC-BY-SA (v3.0 or later)
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/proj-datumgrid-europe-1.3-0.tar.bz2
md5         : 45498c111e287505f9892f460844ee65
timestamp   : 2019-07-05 19:22:07 UTC
dependencies: []
...
```

**Comment by xylar** [comment]
@ocefpaf, looking into this a bit further, maybe it's fine that `proj` isn't pinned?  These grids aren't very useful without it but there's no need to pin a specific version, maybe.  Anyway, I'm happy to either explicitly add `proj` as a dependency and rerender or just close this PR, whichever you recommend.

**Comment by ocefpaf** [comment]
> @ocefpaf, looking into this a bit further, maybe it's fine that `proj` isn't pinned? These grids aren't very useful without it but there's no need to pin a specific version, maybe. Anyway, I'm happy to either explicitly add `proj` as a dependency and rerender or just close this PR, whichever you recommend.

I don't know of any use of the grids without `proj` but  in theory `proj` should require one, the global grid, and the others are optional. I'm not against adding `proj` as a dependency to all sub-packages but I don't think we need to.

Merging this to get you as a maintainer and, if you feel strong  about having the grids install proj, feel free to send another PR and merge it.

**Pull request merged**
